export const projects = [
  {
    id: 1,
    short: "S. BERMEJO",
    title: "Sinahi Bermejo — Lashes & Brows",
    type: "Sitio profesional",
    urlLabel: "sinahibermejo.com",
    description: "Sitio profesional desarrollado para un estudio de pestañas, cejas y micropigmentación. Presenta sus servicios, trabajo, información profesional, ubicación y medios de contacto de forma clara, visual y adaptable a distintos dispositivos.",
    tecnologias: ["React", "JavaScript", "Tailwind CSS"],
    live: "https://sinahibermejo.com/",
    github: null,
    images: [
      "/PROYECTOS/sinahi/a.png",
      "/PROYECTOS/sinahi/b.png",
      "/PROYECTOS/sinahi/c.png",
      "/PROYECTOS/sinahi/d.png",
      "/PROYECTOS/sinahi/e.png",
      "/PROYECTOS/sinahi/f.png",
      "/PROYECTOS/sinahi/g.png",
      "/PROYECTOS/sinahi/h.png",
      "/PROYECTOS/sinahi/i.png",
      "/PROYECTOS/sinahi/j.png",
      "/PROYECTOS/sinahi/k.png",
    ],
  },
  {
    id: 2,
    short: "CEBALLOS",
    title: "Ceballos Artículos Religiosos",
    type: "Sitio web comercial",
    urlLabel: "religiososceballos.com",
    description: "Sitio web comercial para una tienda de artículos religiosos. Organiza sus productos por categorías, presenta rosarios, galería, historia del negocio, ubicación y medios de contacto, con integración directa a WhatsApp y una interfaz elegante adaptable a modo claro y oscuro.",
    tecnologias: ["React", "JavaScript", "Tailwind CSS"],
    live: "https://religiososceballos.com/",
    github: null,
    images: [
      "/PROYECTOS/ceballos/a.png",
      "/PROYECTOS/ceballos/b.png",
      "/PROYECTOS/ceballos/c.png",
      "/PROYECTOS/ceballos/d.png",
      "/PROYECTOS/ceballos/e.png",
      "/PROYECTOS/ceballos/f.png",
      "/PROYECTOS/ceballos/g.png",
      "/PROYECTOS/ceballos/h.png",
      "/PROYECTOS/ceballos/i.png",
    ],
  },
  {
    id: 3,
    short: "CROSH AMIGURUMIS",
    title: "Crosh Amigurumis",
    type: "Catálogo / Sitio web",
    urlLabel: "crosh-amigurumis.vercel.app",
    description: "Sitio web creado para presentar amigurumis elaborados a mano mediante un catálogo visual atractivo y organizado. Permite conocer las piezas disponibles y explorar el trabajo artesanal de la marca de una forma sencilla y agradable.",
    tecnologias: ["React", "Vite", "Tailwind CSS", "JavaScript"],
    live: "https://crosh-amigurumis.vercel.app/",
    github: null,
    images: [
      "/PROYECTOS/croshamigurumis/a.png",
      "/PROYECTOS/croshamigurumis/b.png",
      "/PROYECTOS/croshamigurumis/c.png",
      "/PROYECTOS/croshamigurumis/d.png",
      "/PROYECTOS/croshamigurumis/e.png",
      "/PROYECTOS/croshamigurumis/f.png",
      "/PROYECTOS/croshamigurumis/g.png",
      "/PROYECTOS/croshamigurumis/h.png",
      "/PROYECTOS/croshamigurumis/i.png",
    ],
  },
  {
    id: 4,
    short: "ROSITA",
    title: "Rosita",
    type: "Sistema de pedidos",
    urlLabel: "Pedidos por WhatsApp",
    description: "Sistema web para un restaurante orientado a facilitar la toma de pedidos. El usuario puede consultar el menú, seleccionar sus productos y preparar su pedido para enviarlo directamente al negocio mediante WhatsApp.",
    tecnologias: ["React", "Vite", "Tailwind CSS", "JavaScript"],
    live: null,
    github: null,
    images: [
      "/PROYECTOS/rosita/a.png",
      "/PROYECTOS/rosita/b.png",
      "/PROYECTOS/rosita/c.png",
      "/PROYECTOS/rosita/d.png",
    ],
  },
].map(project => ({ ...project, mobileImages: [...project.images] }));