import {
    BriefcaseBusiness,
    GraduationCap,
    FolderGit2,
    Brain,
    Trophy,
    Wrench,
    Monitor,
    Cpu,
    PencilRuler,
    Cable,
    Printer,
    FileCode2,
    GitBranch,
    Globe,
    Code2,
    BookOpen,
    Users,
} from "lucide-react";

const logoTemporal = "./PROYECTOS/Stickers.png";

export const Experiencias = [
    {
        id: 4,
        icono: FolderGit2,
        logo: logoTemporal,
        puesto: "Frontend Developer Jr.",
        empresa: "Proyectos Personales",
        ubicacion: "Remoto",
        fecha: "Junio 2025 – Actualidad",
        tipo: "Personal",
        descripcion:
            "Desarrollo de aplicaciones web con React, JavaScript y Tailwind CSS, enfocadas en interfaces modernas, responsivas e integración de APIs REST.",
        responsabilidades: [
            "Desarrollo de aplicaciones web utilizando React, JavaScript y Tailwind CSS.",
            "Creación de interfaces modernas y responsivas.",
            "Integración de APIs REST.",
            "Gestión de versiones mediante Git y GitHub.",
            "Despliegue de aplicaciones utilizando Vercel.",
        ],
        seccionExtra: {
            titulo: "Logros",
            icono: Trophy,
            contenido: [
                "Desarrollo de Crosh Amigurumis como proyecto completo.",
                "Sitio profesional para Sinahi Bermejo Lashes & Brows.",
                "Diseño y desarrollo de un portafolio personal desde cero.",
                "Aplicación de buenas prácticas de organización de componentes y diseño responsive.",
            ],
        },
        tecnologias: [
            { nombre: "React", icono: FileCode2 },
            { nombre: "JavaScript", icono: Code2 },
            { nombre: "Tailwind CSS", icono: Code2 },
            { nombre: "Git", icono: GitBranch },
            { nombre: "GitHub", icono: GitBranch },
            { nombre: "Vercel", icono: Globe },
        ],
    },
    {
        id: 3,
        icono: BookOpen,
        logo: logoTemporal,
        puesto: "Tutora de Programación",
        empresa: "Freelance",
        ubicacion: "Remoto",
        fecha: "Febrero 2025 – Actualidad",
        tipo: "Freelance",
        descripcion:
            "Acompañamiento en fundamentos de programación y desarrollo web, con énfasis en lógica, resolución de problemas y tecnologías frontend.",
        responsabilidades: [
            "Impartición de fundamentos de programación y desarrollo web.",
            "Asesoría en JavaScript, HTML, CSS, Tailwind CSS, C# y C++.",
            "Fortalecimiento de lógica de programación y resolución de problemas.",
        ],
        seccionExtra: {
            titulo: "Habilidades desarrolladas",
            icono: Users,
            contenido: [
                "Comunicación clara de conceptos técnicos.",
                "Adaptación de explicaciones al nivel de cada persona.",
                "Organización de sesiones y seguimiento de avances.",
            ],
        },
        tecnologias: [
            { nombre: "JavaScript", icono: Code2 },
            { nombre: "HTML", icono: FileCode2 },
            { nombre: "CSS", icono: Code2 },
            { nombre: "Tailwind CSS", icono: Code2 },
            { nombre: "C#", icono: FileCode2 },
            { nombre: "C++", icono: FileCode2 },
        ],
    },
    {
        id: 2,
        icono: BriefcaseBusiness,
        logo: logoTemporal,
        puesto: "Ingeniera en Automatización",
        empresa: "Jabil",
        ubicacion: "Zapopan, Jalisco",
        fecha: "Octubre 2024 – Mayo 2025",
        tipo: "Tiempo completo",
        descripcion:
            "Diagnóstico y resolución de incidencias en equipos automatizados, con documentación técnica y colaboración con equipos multidisciplinarios.",
        responsabilidades: [
            "Diagnóstico y resolución de incidencias en equipos automatizados.",
            "Elaboración y actualización de documentación técnica.",
            "Colaboración con equipos multidisciplinarios para la solución de problemas operativos.",
        ],
        seccionExtra: {
            titulo: "Habilidades desarrolladas",
            icono: Brain,
            contenido: [
                "Diagnóstico inicial de fallas en equipos automatizados.",
                "Configuración mediante interfaces HMI.",
                "Resolución de incidencias operativas.",
                "Trabajo bajo presión en entornos de producción.",
                "Comunicación y colaboración con operadores y técnicos.",
            ],
        },
        tecnologias: [
            { nombre: "HMI", icono: Monitor },
            { nombre: "Grippers", icono: Wrench },
            { nombre: "Feeders", icono: Cpu },
        ],
    },
    {
        id: 1,
        icono: GraduationCap,
        logo: logoTemporal,
        puesto: "Practicante de Ingeniería",
        empresa: "HV Solutions",
        ubicacion: "Colima, Colima",
        fecha: "Febrero 2024 – Junio 2024",
        tipo: "Prácticas Profesionales",
        descripcion:
            "Apoyo en programación básica de PLC y participación en pruebas, validación y documentación técnica de proyectos de automatización.",
        responsabilidades: [
            "Apoyo en programación básica de PLC Allen Bradley y Siemens.",
            "Participación en pruebas, validación y documentación técnica.",
        ],
        seccionExtra: {
            titulo: "Habilidades desarrolladas",
            icono: Brain,
            contenido: [
                "Interpretación de planos eléctricos.",
                "Diseño técnico con AutoCAD.",
                "Integración básica PLC-HMI.",
                "Trabajo en proyectos de automatización.",
            ],
        },
        tecnologias: [
            { nombre: "AutoCAD", icono: PencilRuler },
            { nombre: "PLC", icono: Cpu },
            { nombre: "HMI", icono: Monitor },
            { nombre: "Cableado", icono: Cable },
            { nombre: "Impresión 3D", icono: Printer },
        ],
    },
];
